== 基本的な文法 ==

ここでは、Asciidocの基本的な書き方について説明します。
処理系として `Asciidoctor` を想定していますが、他のツールでもほぼ互換性があるはずです。

=== ファイル構成 ===

Asciidocのファイルは、 `ファイル名.adoc` のように拡張子を `.adoc` とするのが一般的です。
また、文字コードはUTF-8とする必要があります。

Asciidocでは、1つの文書を複数のファイルに分割もできます。

=== 見出し ===

文書を構造化するには、章、節などのまとまりに分割し、見出しを付けることが重要です。

Asciidocでは、`=`(イコール)を並べて文字を囲むことで、その部分が見出しになります。

-------------------------------------------------------------------------------
= 文書のタイトル =

== 見出し1 (章) ==

=== 見出し2 (節) ===

==== 見出し3 (小節) ====

===== 見出し4 (小々節) =====
-------------------------------------------------------------------------------

=== 段落 ===

長い文書を書くときは、空白行を挟むことで段落分けすることができます。例えば、次のようにします。

-------------------------------------------------------------------------------
空白行までが1つの段落と認識されます。そのため、テキスト中の好きな場
所で改行することができます。
改行を入れただけだと、出力時に同じ段落とみなされ、改行は取り除かれます。

このように空白行を挟むことで、次の段落として出力されます。
-------------------------------------------------------------------------------

これは、次のように出力されます。

*******************************************************************************
空白行までが1つの段落と認識されます。そのため、テキスト中の好きな場
所で改行することができます。
改行を入れただけだと、出力時に同じ段落とみなされ、改行は取り除かれます。

このように空白行を挟むことで、次の段落として出力されます。
*******************************************************************************


また、見出し付きの段落を書くこともできます。

-------------------------------------------------------------------------------
.見出し付きの段落
普通の段落ではなく、見出しのついた段落です。
-------------------------------------------------------------------------------

これは、次のように出力されます。

*******************************************************************************
.見出し付きの段落の例
普通の段落ではなく、見出しのついた段落です。
*******************************************************************************

=== 文章の装飾 ===

読みやすい文書を書くには、 **キーワード** を太字で書いたり、 __固有名詞__ を斜体で書くなどの工夫が有効です。

-------------------------------------------------------------------------------
**太字** 、 __斜体__ 、 ++等幅文字++ などが利用できます。
-------------------------------------------------------------------------------

これは、次のように出力されます。

*******************************************************************************
**太字** 、 __斜体__ 、 ++等幅文字++ などが利用できます。
*******************************************************************************

文書中にソースコードやコマンドなどを見栄え良く埋め込むこともできます。

-------------------------------------------------------------------------------
C言語で"Hello, world"を出力するには、 `printf("Hello, world!");` とします。
-------------------------------------------------------------------------------

これは、次のように出力されます。

*******************************************************************************
C言語で"Hello, world"を出力するには、 `printf("Hello, world!");` とします。
*******************************************************************************

注意点として、日本語文書で装飾を行う場合は、前後にスペースを入れないと崩れて表示さるケースがあります。

=== 箇条書き ===

箇条書きを簡単に作ることができます。

-------------------------------------------------------------------------------
  * 1年生
    - 1年1組
  * 2年生
    - 2年1組
    - 2年2組
-------------------------------------------------------------------------------

これは、次のように出力されます。

  * 1年生
    - 1年1組
  * 2年生
    - 2年1組
    - 2年2組

番号付き箇条書きは、次のように書けます。

-------------------------------------------------------------------------------
  . 近畿
    .. 大阪
    .. 兵庫
  . 中国
    .. 岡山
    .. 広島
-------------------------------------------------------------------------------

次のように出力されます。

  . 近畿
    .. 大阪
    .. 兵庫
  . 中国
    .. 岡山
    .. 広島

=== 定義リスト ===

用語の定義などを説明するのに便利です。

AsciiDoc::
    文書整形ツール
AsciiDoctor::
    文書ツール

=== ソースコード ===

.C言語のHello, world!
[source,c]
-------------------------------------------------------------------------------
#include <stdio.h>

int main(void)
{
    printf("Hello, world!");
    return 0;
}
-------------------------------------------------------------------------------


=== 表 ===

.表の例
[options="header,footer"]
|=================================
|カラム 1|カラム 2      |カラム 3
|1       |アイテム 1    |a
|2       |アイテム 2    |b
|3       |アイテム 3    |c
|合計6   |Three items   |d
|=================================

